version: '3'
services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    env_file: private.env
    devices: 
      - /dev/tty0
    restart: always
    depends_on:
      - database

  database:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: bluetide
      POSTGRES_DB: gatomalo
